function [X] = spline_functions(x,tau,dx,k,M)

X = zeros(k+M,length(x));

% i = 1
X(1,:) = (1/dx^3)*(tau(M+1)-x).*(tau(M+1)-x).*(tau(M+1)-x).*(tau(M)<=x).*(x<tau(M+1));

% i = 2
X(2,:) = (1/dx^3)*(x-tau(2)).*(tau(M+1)-x).*(tau(M+1)-x).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/2/dx^3)*(tau(M+2)-x).*(x-tau(3)).*(tau(M+1)-x).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/4/dx^3)*(tau(M+2)-x).*(tau(M+2)-x).*(x-tau(M)).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/4/dx^3)*(tau(M+2)-x).*(tau(M+2)-x).*(tau(M+2)-x).*(tau(M+1)<=x).*(x<tau(M+2));

% i = 3
X(3,:) = (1/2/dx^3)*(x-tau(3)).*(x-tau(3)).*(tau(M+1)-x).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/4/dx^3)*(x-tau(3)).*(tau(M+2)-x).*(x-tau(M)).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/4/dx^3)*(x-tau(3)).*(tau(M+2)-x).*(tau(M+2)-x).*(tau(M+1)<=x).*(x<tau(M+2)) ...
       + (1/6/dx^3)*(tau(M+3)-x).*(x-tau(M)).*(x-tau(M)).*(tau(M)<=x).*(x<tau(M+1)) ...
       + (1/6/dx^3)*(tau(M+3)-x).*(x-tau(M)).*(tau(M+2)-x).*(tau(M+1)<=x).*(x<tau(M+2)) ...
       + (1/6/dx^3)*(tau(M+3)-x).*(tau(M+3)-x).*(x-tau(M+1)).*(tau(M+1)<=x).*(x<tau(M+2)) ...
       + (1/6/dx^3)*(tau(M+3)-x).*(tau(M+3)-x).*(tau(M+3)-x).*(tau(M+2)<=x).*(x<tau(M+3));
       
% i = 4,...,k + 1
for i = M:(k + 1)
 X(i,:) = (1/6/dx^3)*(x-tau(i)).*(x-tau(i)).*(x-tau(i)).*(tau(i)<=x).*(x<tau(i+1)) ...
        + (1/6/dx^3)*(x-tau(i)).*(x-tau(i)).*(tau(i+2)-x).*(tau(i+1)<=x).*(x<tau(i+2)) ...
        + (1/6/dx^3)*(x-tau(i)).*(tau(i+3)-x).*(x-tau(i+1)).*(tau(i+1)<=x).*(x<tau(i+2)) ...
        + (1/6/dx^3)*(x-tau(i)).*(tau(i+3)-x).*(tau(i+3)-x).*(tau(i+2)<=x).*(x<tau(i+3)) ...
        + (1/6/dx^3)*(tau(i+4)-x).*(x-tau(i+1)).*(x-tau(i+1)).*(tau(i+1)<=x).*(x<tau(i+2)) ...
        + (1/6/dx^3)*(tau(i+4)-x).*(x-tau(i+1)).*(tau(i+3)-x).*(tau(i+2)<=x).*(x<tau(i+3)) ...
        + (1/6/dx^3)*(tau(i+4)-x).*(tau(i+4)-x).*(x-tau(i+2)).*(tau(i+2)<=x).*(x<tau(i+3)) ...
        + (1/6/dx^3)*(tau(i+4)-x).*(tau(i+4)-x).*(tau(i+4)-x).*(tau(i+3)<=x).*(x<tau(i+4));   
end    

% i = k + 2
X(k+2,:) =  -(1/6/dx^3)*(tau(k+2)-x).*(tau(k+2)-x).*(tau(k+2)-x).*(tau(k+2)<=x).*(x<tau(k+3)) ...
       - (1/6/dx^3)*(tau(k+2)-x).*(tau(k+2)-x).*(x-tau(k+4)).*(tau(k+3)<=x).*(x<tau(k+4)) ...
       - (1/6/dx^3)*(tau(k+2)-x).*(x-tau(k+5)).*(tau(k+3)-x).*(tau(k+3)<=x).*(x<tau(k+4)) ...
       - (1/6/dx^3)*(tau(k+2)-x).*(x-tau(k+5)).*(x-tau(k+5)).*(tau(k+4)<=x).*(x<tau(k+5)) ...       
       - (1/4/dx^3)*(x-tau(k+6)).*(tau(k+3)-x).*(tau(k+3)-x).*(tau(k+3)<=x).*(x<tau(k+4)) ...
       - (1/4/dx^3)*(x-tau(k+6)).*(tau(k+3)-x).*(x-tau(k+5)).*(tau(k+4)<=x).*(x<tau(k+5)) ...
       - (1/2/dx^3)*(x-tau(k+6)).*(x-tau(k+6)).*(tau(k+4)-x).*(tau(k+4)<=x).*(x<tau(k+5));
   
% i = k + 3
X(k+3,:) = - (1/4/dx^3)*(tau(k+3)-x).*(tau(k+3)-x).*(tau(k+3)-x).*(tau(k+3)<=x).*(x<tau(k+4)) ...
           - (1/4/dx^3)*(tau(k+3)-x).*(tau(k+3)-x).*(x-tau(k+5)).*(tau(k+4)<=x).*(x<tau(k+5)) ...
           - (1/2/dx^3)*(tau(k+3)-x).*(x-tau(k+6)).*(tau(k+4)-x).*(tau(k+4)<=x).*(x<tau(k+5)) ...
           - (1/dx^3)*(x-tau(k+7)).*(tau(k+4)-x).*(tau(k+4)-x).*(tau(k+4)<=x).*(x<tau(k+5));

% i = k + 4
X(k+4,:) = -(1/dx^3)*(tau(k+4)-x).*(tau(k+4)-x).*(tau(k+4)-x).*(tau(k+4)<=x).*(x<=tau(k+5));

X = X';
